== Spring Boot Example with Camel REST DSL and OpenApi

=== Introduction

This example illustrates how to use https://projects.spring.io/spring-boot/[Spring Boot] with http://camel.apache.org[Camel]. It provides a simple REST service that is created with http://camel.apache.org/rest-dsl.html[Camel REST DSL] and documented with http://swagger.io[OpenApi].

The project uses the `camel-spring-boot-starter` dependency, a Spring Boot starter dependency for Camel that simplifies the Maven configuration.

The project also uses `camel-servlet` component as the HTTP transport component for Camel REST DSL.

=== Build

You can build this example using:

    $ mvn package

=== Run

You can run this example using:

    $ mvn spring-boot:run

You should see the following output when the application is launched:

[source,text]
----
...
[INFO] >>> spring-boot-maven-plugin:2.7.13:run (default-cli) > test-compile @ rest-openapi >>>
[...]
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.13)

2023-07-28 16:05:57.811  INFO 93251 --- [           main] hs.example.camel.springboot.Application  : Starting Application using Java 17.0.6 on hosukui-MacBookPro.local with PID 93251 (/Users/hosuk/hs/camel-example/camel-springboot/rest-openapi/target/classes started by hosuk in /Users/hosuk/hs/camel-example/camel-springboot/rest-openapi)
2023-07-28 16:05:57.818  INFO 93251 --- [           main] hs.example.camel.springboot.Application  : No active profile set, falling back to 1 default profile: "default"
2023-07-28 16:05:59.250  WARN 93251 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2023-07-28 16:05:59.266  INFO 93251 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
[...]
2023-07-28 16:06:00.862  INFO 93251 --- [           main] o.a.c.impl.engine.AbstractCamelContext   : Apache Camel 3.21.0 (MyCamel) started in 288ms (build:34ms init:233ms start:21ms)
2023-07-28 16:06:00.867  INFO 93251 --- [           main] hs.example.camel.springboot.Application  : Started Application in 3.524 seconds (JVM running for 3.998)
----

After the Spring Boot application is started, you can open the following URL in your web browser to access the REST endpoint and retrieve a list of users: http://localhost:8080/api/users

You can also access the REST endpoint from the command line:

[source,text]
----
$ curl http://localhost:8080/api/users
----

The command will produce the following output:

[source,json]
----
[ {
  "id" : 1,
  "name" : "John Coltrane"
}, {
  "id" : 2,
  "name" : "Miles Davis"
}, {
  "id" : 3,
  "name" : "Sonny Rollins"
} ]
----

The OpenApi documentation is located at: `\http://localhost:8080/api/api-doc` and can be retrieved with the following command:

[source,text]
----
$ curl http://localhost:8080/api/api-doc
----

The Spring Boot application can be stopped pressing `[CTRL] + [C]` in the shell.